name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build exe
      run: |
        pyinstaller --noconfirm --onefile --windowed main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartClassroom
        path: dist/main.exe
